# Generated by Django 3.2.4 on 2021-06-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210615_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='updated',
        ),
    ]
