# Generated by Django 3.2.4 on 2021-06-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(null=True),
        ),
    ]
